### ISSUE TITLE
name 'joystick' is not defined

### ISSUE THREAD

**Issue by sevmardi** [JavaFXpert/quantum-pong#1]
Hi! 
Running the main.py file shows the following error. 
```
File "main.py", line 183, in main
 joystick_hat = joystick.get_hat(0)
```

**Comment by JavaFXpert** [comment]
Is a gamepad connected?

On Wed, Mar 6, 2019, at 2:44 PM, Sevak Mardirosian wrote:

> Hi!
>  Running the main.py file shows the following error.

> `File "main.py", line 183, in main
 joystick_hat = joystick.get_hat(0)
`

**Comment by sevmardi** [comment]
Sorry something was wrong on my side. Works now.

**Comment by JavaFXpert** [comment]
You might want to contact Junye who created much of the paddle indeed ball logic, anis carrying the development forward here: https://github.com/HuangJunye/QPong

Regards,
James (Jim) Weaver
